#!/bin/bash
# @author Zachary Wartell
# @brief

# ITCS_x120_HTML-CSS-Event_Tutorial

# replace the string $REVISION$ with the git log's date of last revision in the file index.html
#sed -i -e s/[$]REVISION[$]/"$(git log --format=format:\"%cD\" HEAD@{1}..HEAD)"/ .public/index.html
echo -n '<span class="Revision">' > REVISION.txt
echo -n `git show --no-patch --no-notes --pretty='%cd'` >> REVISION.txt
echo -n '<\/span>' >> REVISION.txt
sed -i -e s/'<span class="Revision">.*<\/span>'/"$(cat REVISION.txt)"/ "../ITCS_x120_HTML-CSS-Event_Tutorial.html"
#exit

rm ftp.cmd
echo cd 'public_html/Teaching/ITCS_x120_HTML-CSS-Event_Tutorial'  > ftp.cmd
echo lcd '..'                                 >> ftp.cmd
echo put -R . .                               >> ftp.cmd

sftp 'zwartell@webpages.uncc.edu' < ftp.cmd
