#!/bin/bash
#  This script should be run from the directory containing it, i.e. zjw-generic-instructions-template/site/git_modules/zjwgi/scripts/zjwgi
# init-template [%1] [%2]

# %1 is an opational prefix for the directory name containing the files published to the public website
#     one common option is:
#         www-

# references
# - https://man7.org/linux/man-pages/man1/getopts.1p.html

echo This script should be run from the directory containing it, i.e. zjw-generic-instructions-template/site/git_modules/zjwgi/scripts/zjwgi

USAGE_D="%s [-h] [-p path-prefix] [-r relative-path] [-z relative-path]"
USAGE_P="   
    -h                      shows this help
    -p value                (--dir-prefix) optional prefix to name of directory name containing the files published to the public website. The prefix is prepended to standard name directory name: 'site'.
    -r value                (--root-path) optional relative path too root directory of the project folder [Default:  ../../../..]
    -z value                (--zjwgi-path) optional relative path too root directory of the zjwgi folder [Default:  ../../$SITE/git_modules/zjwgi]
"
     
DirPrefix=
RootPath="../../../.."
ZJWGIPath=

while getopts p:r:z: name; do
    case $name in    
    p)  DirPrefix="$OPTARG"
        ;;    
    r)  RootPath="$OPTARG"
        ;;    
    z)  ZJWGIPath="$OPTARG"
        ;;    
    h)
        printf "$USAGE_P" `basename "$0"`
        printf "$USAGE_D" `basename "$0"`
        exit 2
        ;;
    esac
done

pushd $RootPath

SITE={$DirPrefix}site

#if /i "$ZJWGIPath"=="" set "ZJWGIPath=../$SITE/git_modules/zjwgi"

pwd

rmdir scripts/zjwgi 2>null ;        ln -s scripts/zjwgi        "$ZJWGIPath/scripts"
mkdir $SITE/css > nul 2>&1
rmdir $SITE/css/zjwgi 2>null ;      ln -s $SITE/css/zjwgi      "../$ZJWGIPath/site/css/zjwgi"
mkdir $SITE/html > nul 2>&1
rmdir $SITE/html/zjwgi 2>null ;     ln -s $SITE/html/zjwgi     "../$ZJWGIPath/site/html/zjwgi"
mkdir $SITE/scripts > nul 2>&1
rmdir $SITE/scripts/zjwgi 2>null ;  ln -s $SITE/scripts/zjwgi  "../$ZJWGIPath/site/scripts/zjwgi"

mkdir $SITE/images > nul 2>&1
rmdir $SITE/images/zjwgi 2>null ;   ln -s $SITE/images/zjwgi   "../$ZJWGIPath/site/images/zjwgi"

mkdir $SITE/videos > nul 2>&1
rmdir $SITE/videos/zjwgi 2>null ;   ln -s $SITE/videos/zjwgi   "../$ZJWGIPath/site/videos/zjwgi"
# \todo ??? copy /-Y $SITE/git_modules/zjwgi/site/index.html $SITE           

popd