#!/bin/bash
#
# SOURCE: https://www.digitalocean.com/community/tutorials/how-to-find-broken-links-on-your-website-using-wget-on-debian-7
#
wget --spider -r -nd -nv -H -l 1 -w 2 -o run1.log "https://zwartell.gitlab.io/javascript-tutorial/index.html"
grep -B1 "broken link!" run1.log
