#!/bin/bash
# @author Zachary Wartell
# @brief  publishWWW <path to config file> <path to repo site directory>

# read config file
CONFIG_FILE=$1
ftphost=`grep -e ftphost $CONFIG_FILE | sed 's/\(\S*\s\)\(.*\)/\2/g'`
ftpdir=`grep -e ftpdir $CONFIG_FILE | sed 's/\(\S*\s\)\(.*\)/\2/g'`
ftpuser=`grep -e ftpuser $CONFIG_FILE | sed 's/\(\S*\s\)\(.*\)/\2/g'`
htmlfile=`grep -e htmlfile $CONFIG_FILE | sed 's/\(\S*\s\)\(.*\)/\2/g'`
echo $ftphost
echo $ftpdir
echo $ftpuser
echo $htmlfile
#exit

site_path=$2

site_full_path=$( echo $(cd $(dirname $site_path); pwd)/$(basename $site_path); )
echo site_full_path: $site_full_path

# replace the string $REVISION$ with the git log's date of last revision in the file index.html

#sed -i -e s/[$]REVISION[$]/"$(git log --format=format:\"%cD\" HEAD@{1}..HEAD)"/ .public/index.html
echo -n '<span class="Revision">' > REVISION.txt
echo -n `git show --no-patch --no-notes --pretty='%cd'` >> REVISION.txt
echo -n '<\/span>' >> REVISION.txt
sed -i -e s/'<span class="Revision">.*<\/span>'/"$(cat REVISION.txt)"/ "$site_full_path/$htmlfile"
#exit

read -p 'Revison Update.  Proceed with mirror update? [y/n]' yn
echo yn: $yn
if [ $yn != "y" -a $yn != "Y" ] ; then
    exit
fi

# sftp ../site contents to target
#rm ftp.cmd &2> /dev/null

pushd "$site_full_path/.."
mkdir -p www-site-mirror

if [[  $# -eq 3 && $3 == 'old-org' ]] ; then
    cp -r -u -L "$site_full_path/*.html" www-site-mirror
    cp -r -u -L "$site_full_path/css" www-site-mirror
    cp -r -u -L "$site_full_path/html" www-site-mirror
    cp -r -u -L "$site_full_path/scripts" www-site-mirror
    cp -r -u -L "$site_full_path/images" www-site-mirror
    cp -r -u -L "$site_full_path/videos" www-site-mirror
    mkdir -p www-site-mirror/git-modules/zjw-generic-instructions/site/css/zjwgi
    mkdir -p www-site-mirror/git-modules/zjw-generic-instructions/site/html/zjwgi
    mkdir -p www-site-mirror/git-modules/zjw-generic-instructions/site/scripts/zjwgi
    mkdir -p www-site-mirror/git-modules/zjw-generic-instructions/site/video/zjwgi
    cp -r -u -L "$site_full_path/git-modules/zjw-generic-instructions/site/css/zjwgi"     www-site-mirror/git-modules/zjw-generic-instructions/site/css/
    cp -r -u -L "$site_full_path/git-modules/zjw-generic-instructions/site/scripts/zjwgi" www-site-mirror/git-modules/zjw-generic-instructions/site/scripts/
    cp -r -u -L "$site_full_path/git-modules/zjw-generic-instructions/site/html/zjwgi"    www-site-mirror/git-modules/zjw-generic-instructions/site/html/   
    cp -r -u -L "$site_full_path/git-modules/zjw-generic-instructions/site/video/zjwgi"   www-site-mirror/git-modules/zjw-generic-instructions/site/video/
else
    cp -u -L "$site_full_path/"*.html  www-site-mirror
    cp -r -u -L "$site_full_path/css"     www-site-mirror
    cp -r -u -L "$site_full_path/html"    www-site-mirror
    cp -r -u -L "$site_full_path/scripts" www-site-mirror
    cp -r -u -L "$site_full_path/images"  www-site-mirror
    cp -r -u -L "$site_full_path/videos"  www-site-mirror
fi    
popd


read -p 'www-site-mirror Update.  Proceed with sftp? [y/n]' yn
if [ $yn != "y" -a $yn != "Y" ] ; then
    exit
fi

pushd "$site_full_path/.."

echo cd "$ftpdir"                   > ftp.cmd
echo lcd www-site-mirror            >> ftp.cmd
echo put -R . .                     >> ftp.cmd
cat ftp.cmd
sftp $ftpuser@$ftphost < ftp.cmd

popd